export { cache } from './lib/cache'
export { config } from './lib/config'
export { default as extensions } from './lib/extensions'
export { extract } from './lib/extract'
export { fetch } from './lib/fetch'
export { install } from './lib/install'
export { support } from './lib/support'
export { verify } from './lib/verify'
